version: '3.9'
services:
    gateway:
        image: ${REGISTRY}/auction-testing-gateway:${IMAGE_TAG}

    frontend:
        image: ${REGISTRY}/auction-frontend:${IMAGE_TAG}

    api:
        image: ${REGISTRY}/auction-api:${IMAGE_TAG}

    api-php-fpm:
        image: ${REGISTRY}/auction-api-php-fpm:${IMAGE_TAG}
        depends_on:
            - api-postgres
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app-test.org
            FRONTEND_URL: http://gateway:8083
            SENTRY_DSN: ''
            JWT_ENCRYPTION_KEY: jwt_secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        secrets:
          - jwt_public_key
          - jwt_private_key

    api-php-cli:
        image: ${REGISTRY}/auction-api-php-cli:${IMAGE_TAG}
        depends_on:
            - api-postgres
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app-test.org
            FRONTEND_URL: http://gateway:8083
            SENTRY_DSN: ''
            JWT_ENCRYPTION_KEY: jwt_secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        secrets:
          - jwt_public_key
          - jwt_private_key

    testing-api-php-cli:
        image: ${REGISTRY}/auction-testing-api-php-cli:${IMAGE_TAG}
        depends_on:
            - api-postgres
        environment:
            APP_ENV: dev
            APP_DEBUG: 1
            DB_HOST: api-postgres
            DB_USER: app
            DB_PASSWORD: secret
            DB_NAME: app
            MAILER_HOST: mailer
            MAILER_PORT: 1025
            MAILER_USERNAME: app
            MAILER_PASSWORD: secret
            MAILER_ENCRYPTION: tcp
            MAILER_FROM_EMAIL: mail@app-test.org
            FRONTEND_URL: http://gateway:8083
            SENTRY_DSN: ''
            JWT_ENCRYPTION_KEY: jwt_secret
            JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
            JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
        secrets:
          - jwt_public_key
          - jwt_private_key

    api-postgres:
        image: postgres:14.4-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - '54324:5432'

    mailer:
        image: mailhog/mailhog

    cucumber-node-cli:
        image: ${REGISTRY}/auction-cucumber-node-cli:${IMAGE_TAG}
        volumes:
            - ./cucumber/var:/app/var

secrets:
    jwt_public_key:
        file: ./docker/development/secrets/jwt_public_key
    jwt_private_key:
        file: ./docker/development/secrets/jwt_private_key